[package]
name = "async-process"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "1.4.0"
cfg-if = "0.1.10"
futures-lite = "0.1.11"
once_cell = "1.4.1"

[target.'cfg(unix)'.dependencies]
async-io = "0.1.11"
signal-hook = { version = "0.1.16", default-features = false }

[target.'cfg(windows)'.dependencies]
blocking = "0.5.1"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
features = [
  "handleapi",
  "winerror",
  "minwindef",
  "processthreadsapi",
  "synchapi",
  "threadpoollegacyapiset",
  "winbase",
  "winnt",
]
